
name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      
jobs:
  container:
    runs-on: ubuntu-latest
    container: ballerina/ballerina:swan-lake-beta1
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: |
          ./gradlew build -Prelease=false
