
name: Release

on:
  push:
    branches: [ master ]
    
jobs:
  container:
    runs-on: ubuntu-latest
    container: kanishkaw/openapi-dist
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -al  
      - name: Build with Gradle
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: |
           ./gradlew build -Prelease=true
