name: Test GitHub Actions 

on:
  push:
    branches:
      - "master"

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run pwd
        run: pwd
      - name: list
        run: ls
      - name: list previous folder
        run: ls ../
